[package]
name = "vulkan-rust-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nobs-vk = "0.2.0"
winit = "0.29.9"
